
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.util.Scanner;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author briao
 */
public class createAccount extends javax.swing.JFrame {
        //this class is for customer account creation i.e. append info 
        //customerList.txt
    static String acctype;
    static String ccNum;

    
    public createAccount() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelcreatecustacc = new javax.swing.JLabel();
        jLabelusername = new javax.swing.JLabel();
        jLabelphonenum = new javax.swing.JLabel();
        jLabelpassword = new javax.swing.JLabel();
        jLabeladdress = new javax.swing.JLabel();
        jLabelccnum = new javax.swing.JLabel();
        jTextFieldCAUI_USERNAME = new javax.swing.JTextField();
        jTextFieldCAUI_ADDRESS = new javax.swing.JTextField();
        jTextFieldCAUI_PASSWORD = new javax.swing.JTextField();
        jTextFieldCAUI_PHONENUM = new javax.swing.JTextField();
        jTextFieldCAUI_CCNUM = new javax.swing.JTextField();
        jButtonCREATECUSTOMERACCOUNT = new javax.swing.JButton();
        jRadioButtonREGACCOUNT = new javax.swing.JRadioButton();
        jRadioButtonPREMACCOUNT = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelcreatecustacc.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabelcreatecustacc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelcreatecustacc.setText("Create Customer Account");

        jLabelusername.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelusername.setText("Username :");

        jLabelphonenum.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelphonenum.setText("Phone # :");

        jLabelpassword.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelpassword.setText("Password :");

        jLabeladdress.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabeladdress.setText("Address :");

        jLabelccnum.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelccnum.setText("CC # :");

        jTextFieldCAUI_PASSWORD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCAUI_PASSWORDActionPerformed(evt);
            }
        });

        jTextFieldCAUI_PHONENUM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCAUI_PHONENUMActionPerformed(evt);
            }
        });

        jButtonCREATECUSTOMERACCOUNT.setText("Submit");
        jButtonCREATECUSTOMERACCOUNT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCREATECUSTOMERACCOUNTActionPerformed(evt);
            }
        });

        jRadioButtonREGACCOUNT.setText("regular account (no chg)");

        jRadioButtonPREMACCOUNT.setText("premium account ($40 chg)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(176, 176, 176)
                .addComponent(jButtonCREATECUSTOMERACCOUNT)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jRadioButtonREGACCOUNT)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addComponent(jRadioButtonPREMACCOUNT))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabeladdress)
                        .addGap(50, 50, 50)
                        .addComponent(jTextFieldCAUI_ADDRESS))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabelphonenum)
                        .addGap(45, 45, 45)
                        .addComponent(jTextFieldCAUI_PHONENUM))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabelccnum)
                        .addGap(68, 68, 68)
                        .addComponent(jTextFieldCAUI_CCNUM))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelpassword)
                            .addComponent(jLabelusername))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextFieldCAUI_USERNAME)
                                .addGap(1, 1, 1))
                            .addComponent(jTextFieldCAUI_PASSWORD))))
                .addGap(86, 86, 86))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelcreatecustacc, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(116, 116, 116))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabelcreatecustacc, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelusername)
                    .addComponent(jTextFieldCAUI_USERNAME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelpassword)
                    .addComponent(jTextFieldCAUI_PASSWORD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabeladdress)
                    .addComponent(jTextFieldCAUI_ADDRESS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelphonenum)
                    .addComponent(jTextFieldCAUI_PHONENUM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelccnum)
                    .addComponent(jTextFieldCAUI_CCNUM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonREGACCOUNT)
                    .addComponent(jRadioButtonPREMACCOUNT))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonCREATECUSTOMERACCOUNT)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
//String = jTextFieldUSERNAME.getText();
//        setUserName(username);
    
    private void jTextFieldCAUI_PASSWORDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCAUI_PASSWORDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCAUI_PASSWORDActionPerformed

    private void jTextFieldCAUI_PHONENUMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCAUI_PHONENUMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCAUI_PHONENUMActionPerformed

    public int authenticateUN(String user){
        String compare;
        String filePath = "customerList.txt";
        File file = new File(filePath);
        try{
            Scanner myReader = new Scanner(file);
                while(myReader.hasNextLine()){
                    compare = myReader.nextLine();
                    String[] row = compare.split(",");
                    System.out.println(row[0]);
                    if (user.equals(row[0])){
                        return 0;               
                    }
                }
                myReader.close();
        }catch (FileNotFoundException e) {
            System.out.println("An error occurred.");
            e.printStackTrace();
        }
        return 1;  //if there are no matches, move along
        
        
    }
    private void jButtonCREATECUSTOMERACCOUNTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCREATECUSTOMERACCOUNTActionPerformed
        // writes text file input to customerList.txt file
        String username = jTextFieldCAUI_USERNAME.getText();
        String password = jTextFieldCAUI_PASSWORD.getText();
        String address = jTextFieldCAUI_ADDRESS.getText();
        String phoneNum = jTextFieldCAUI_PHONENUM.getText();
        String ccNum = jTextFieldCAUI_CCNUM.getText();
        String premiumACC = "prem";
        String regularACC = "reg";
        
        String filePath = "customerList.txt";
        String filePath2 = "bankList.txt";
        File file = new File(filePath);
        File file2 = new File(filePath2);
        //String compare;
        
        try{
            FileWriter fw = new FileWriter(file, true);
            BufferedWriter bw = new BufferedWriter(fw); 
            FileWriter fw2 = new FileWriter(file2, true);
            BufferedWriter bw2 = new BufferedWriter(fw2);
            
            if ((jRadioButtonREGACCOUNT.isSelected() == false)&&(jRadioButtonPREMACCOUNT.isSelected() == false)){
                JOptionPane.showMessageDialog(this, "please select an account type");
            }
            if ((jRadioButtonREGACCOUNT.isSelected() == true)&&(jRadioButtonPREMACCOUNT.isSelected() == false)){
                if(authenticateUN(username) == 0){
                    JOptionPane.showMessageDialog(this, "this username already exists, try again");
                    
                }
                else{
                    bw.write("\n" + username + "," + password + "," + address + "," + phoneNum + "," + ccNum + "," + regularACC);
                    bw2.write("\n" + username + "," + ccNum);
                    //bw.newLine();
                    JOptionPane.showMessageDialog(this,"Regular Customer account created");
                    dispose();
                    UserLanding backtolanding = new UserLanding();
                    backtolanding.setVisible(true);
                }
            }
            if ((jRadioButtonREGACCOUNT.isSelected() == false)&&(jRadioButtonPREMACCOUNT.isSelected() == true)){
                if(authenticateUN(username) == 0){
                    JOptionPane.showMessageDialog(this, "this username already exists, try again");
                }
                else{
                    bw.write("\n"+username + "," + password + "," + address + "," + phoneNum + "," + ccNum + "," + premiumACC);
                    bw2.write("\n" + username + "," + ccNum);
                    //bw.newLine();
                    JOptionPane.showMessageDialog(this,"Premium Customer account created");
                    dispose();
                    UserLanding backtolanding = new UserLanding();
                    backtolanding.setVisible(true);
                }
            }
            bw.close();
            fw.close();
            bw2.close();
            fw2.close();
            
        }catch(Exception e){
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_jButtonCREATECUSTOMERACCOUNTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(createAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(createAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(createAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(createAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new createAccount().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCREATECUSTOMERACCOUNT;
    private javax.swing.JLabel jLabeladdress;
    private javax.swing.JLabel jLabelccnum;
    private javax.swing.JLabel jLabelcreatecustacc;
    private javax.swing.JLabel jLabelpassword;
    private javax.swing.JLabel jLabelphonenum;
    private javax.swing.JLabel jLabelusername;
    private javax.swing.JRadioButton jRadioButtonPREMACCOUNT;
    private javax.swing.JRadioButton jRadioButtonREGACCOUNT;
    private javax.swing.JTextField jTextFieldCAUI_ADDRESS;
    private javax.swing.JTextField jTextFieldCAUI_CCNUM;
    private javax.swing.JTextField jTextFieldCAUI_PASSWORD;
    private javax.swing.JTextField jTextFieldCAUI_PHONENUM;
    private javax.swing.JTextField jTextFieldCAUI_USERNAME;
    // End of variables declaration//GEN-END:variables
}
