
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author briao
 */
public class UserLanding extends javax.swing.JFrame {
    static String username;
    static String acctype;
    static String ccNum;

    /**
     * Creates new form UserLanding
     */
    public UserLanding() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButtonCREATECUSTOACCOUNT = new javax.swing.JButton();
        jLabelUSERNAME = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldUSERNAME = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jRadioButtonCUSTOMERACCOUNT = new javax.swing.JRadioButton();
        jRadioButtonSUPPLIERACCOUNT = new javax.swing.JRadioButton();
        jButtonLOGIN = new javax.swing.JButton();
        jButtonEXITAPPLICATION = new javax.swing.JButton();
        jPasswordFieldPASSWORD = new javax.swing.JPasswordField();
        jButtonCREATESUPPACCOUNT = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel1.setText("Welcome to the Shopping System");

        jButtonCREATECUSTOACCOUNT.setText("Create Customer Account");
        jButtonCREATECUSTOACCOUNT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCREATECUSTOACCOUNTActionPerformed(evt);
            }
        });

        jLabelUSERNAME.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelUSERNAME.setText("Username");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Password");

        jTextFieldUSERNAME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUSERNAMEActionPerformed(evt);
            }
        });

        jLabel4.setText("Account Type");

        jRadioButtonCUSTOMERACCOUNT.setText("Customer");
        jRadioButtonCUSTOMERACCOUNT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonCUSTOMERACCOUNTActionPerformed(evt);
            }
        });

        jRadioButtonSUPPLIERACCOUNT.setText("Supplier");

        jButtonLOGIN.setText("Login");
        jButtonLOGIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLOGINActionPerformed(evt);
            }
        });

        jButtonEXITAPPLICATION.setText("Cancel");
        jButtonEXITAPPLICATION.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEXITAPPLICATIONActionPerformed(evt);
            }
        });

        jPasswordFieldPASSWORD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldPASSWORDActionPerformed(evt);
            }
        });

        jButtonCREATESUPPACCOUNT.setText("Create Supplier Account");
        jButtonCREATESUPPACCOUNT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCREATESUPPACCOUNTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelUSERNAME)
                                    .addComponent(jLabel3))
                                .addGap(81, 81, 81)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldUSERNAME, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                                    .addComponent(jPasswordFieldPASSWORD)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addComponent(jLabel4))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jButtonCREATECUSTOACCOUNT)))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadioButtonCUSTOMERACCOUNT)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jRadioButtonSUPPLIERACCOUNT))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonLOGIN)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonEXITAPPLICATION))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                                .addComponent(jButtonCREATESUPPACCOUNT)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel1)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldUSERNAME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelUSERNAME))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jPasswordFieldPASSWORD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jRadioButtonCUSTOMERACCOUNT)
                    .addComponent(jRadioButtonSUPPLIERACCOUNT))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonEXITAPPLICATION)
                    .addComponent(jButtonLOGIN))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCREATESUPPACCOUNT)
                    .addComponent(jButtonCREATECUSTOACCOUNT))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public String getUsername(){
        return username;
    }
    public void setUserName(String in){
        this.username = in;
    }
    public String getacctype(){
        return acctype;
    }
    public void setacctype(String in){
        this.acctype = in;
    }
    
    private void jButtonCREATECUSTOACCOUNTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCREATECUSTOACCOUNTActionPerformed
        dispose();
        createAccount test = new createAccount();
        test.setVisible(true);
    }//GEN-LAST:event_jButtonCREATECUSTOACCOUNTActionPerformed

    private void jTextFieldUSERNAMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUSERNAMEActionPerformed
        
    }//GEN-LAST:event_jTextFieldUSERNAMEActionPerformed
    
    public int authenticateCust(String user, String pass){
        String comp;
        
        String filePath = "customerList.txt";
        File file = new File(filePath);
        try {
            Scanner myReader = new Scanner(file);
            while (myReader.hasNextLine()) {
                // System.out.println(myReader.nextLine());
                comp = myReader.nextLine();
                String[] row = comp.split(",");
                // System.out.println(row[0] + " " + row[1]);       //row[0] = username
                                                                    //row[1] = password in txt file
                 if(row[0].equals(user/*jTextFieldUSERNAME.getText()*/) && row[1].equals(pass/*jTextFieldPASSWORD.getText()*/)){
                    return 1;
                }
            }
            myReader.close();
        } catch (FileNotFoundException e) {
            System.out.println("An error occurred.");
            e.printStackTrace();
        }
        return 0;
    }
    public int authenticateSupp(String user, String pass){
        String comp;
        
        String filePath = "supplierList.txt";
        File file = new File(filePath);
        try {
            Scanner myReader = new Scanner(file);
            while (myReader.hasNextLine()) {
                // System.out.println(myReader.nextLine());
                comp = myReader.nextLine();
                String[] row = comp.split(",");
                // System.out.println(row[0] + " " + row[1]);       //row[0] = username
                                                                    //row[1] = password in txt file
                 if(row[0].equals(user/*jTextFieldUSERNAME.getText()*/) && row[1].equals(pass/*jTextFieldPASSWORD.getText()*/)){
                    return 1;
                }
            }
            myReader.close();
        } catch (FileNotFoundException e) {
            System.out.println("An error occurred.");
            e.printStackTrace();
        }
        return 0;
    }
    public int isUserPremium(String user, String prem){
        String comp;
        
        String filePath = "customerList.txt";
        File file = new File(filePath);
        try {
            Scanner myReader = new Scanner(file);
            while (myReader.hasNextLine()) {
                // System.out.println(myReader.nextLine());
                comp = myReader.nextLine();
                String[] row = comp.split(",");
                //row[0] = username
                //row[5] = account type in txt file
                 if(row[0].equals(user/*jTextFieldUSERNAME.getText()*/) && row[5].equals(prem)/*jTextFieldPASSWORD.getText()*/){
                    return 1;       //1 is premium account
                }
            }
            myReader.close();
        } catch (FileNotFoundException e) {
            System.out.println("An error occurred.");
            e.printStackTrace();
        }
        return 0;   //0 means regular account
    }
    
    private void jButtonLOGINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLOGINActionPerformed
        String tempUsername = jTextFieldUSERNAME.getText();
        setUserName(tempUsername);
        String premiumAccount = "prem";
        String regularAccount = "reg";
        // String password = jTextFieldPASSWORD.getText(); //if i want to use the password controller instead of textfield, use
                                                        //getPassword func, but find a way to convert char[] to String
        String password = new String(jPasswordFieldPASSWORD.getPassword());
       // System.out.println(password);
        if((jRadioButtonSUPPLIERACCOUNT.isSelected() == false)&& (jRadioButtonCUSTOMERACCOUNT.isSelected() == false)){
            JOptionPane.showMessageDialog(this, "please select account type for login");
        }
        //this if statement is for customer
        if((jRadioButtonCUSTOMERACCOUNT.isSelected() == true) && (jRadioButtonSUPPLIERACCOUNT.isSelected()== false))
        {
            
            if(authenticateCust(username, password) == 1){
                if(isUserPremium(username, premiumAccount) == 1){
                    setacctype(premiumAccount);
                   // System.out.println("acctype stores : " + acctype);
                }
                else{
                    setacctype(regularAccount);
                   // System.out.println("acctype stores : " + acctype);

                }
                
            dispose();  //dispose of current window
            DashBoard custDash = new DashBoard();   
            custDash.setVisible(true);  //opens customer dashboard; could be renamed later
            }
        else{
            //pop up box showing no account
            JOptionPane.showMessageDialog(this, "invalid login. please try again or create specified account");
        }
        }
        //this if statement is for supplier verification
        if((jRadioButtonSUPPLIERACCOUNT.isSelected() == true)&& (jRadioButtonCUSTOMERACCOUNT.isSelected() == false))
        {
            if(authenticateSupp(username, password) == 1){
            dispose();  //dispose of current window
            DashBoardSupplier SuppDash = new DashBoardSupplier();   
            SuppDash.setVisible(true);  //opens customer dashboard; could be renamed later
            }
        else{
            //pop up box showing no account
            JOptionPane.showMessageDialog(this, "invalid login. please try again or create specified account");
        }
        }
           //set values once login is confirmed. this means the file should've been written to. Traverse the file based on username and set 
            //values for use in other gui windows
            
        
    }//GEN-LAST:event_jButtonLOGINActionPerformed

    private void jRadioButtonCUSTOMERACCOUNTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonCUSTOMERACCOUNTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonCUSTOMERACCOUNTActionPerformed

    private void jButtonEXITAPPLICATIONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEXITAPPLICATIONActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonEXITAPPLICATIONActionPerformed

    private void jPasswordFieldPASSWORDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldPASSWORDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordFieldPASSWORDActionPerformed

    private void jButtonCREATESUPPACCOUNTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCREATESUPPACCOUNTActionPerformed
        dispose();
        createAccountSUPP createSupp = new createAccountSUPP();
        createSupp.setVisible(true);    }//GEN-LAST:event_jButtonCREATESUPPACCOUNTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserLanding.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserLanding.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserLanding.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserLanding.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserLanding().setVisible(true);                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCREATECUSTOACCOUNT;
    private javax.swing.JButton jButtonCREATESUPPACCOUNT;
    private javax.swing.JButton jButtonEXITAPPLICATION;
    private javax.swing.JButton jButtonLOGIN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelUSERNAME;
    private javax.swing.JPasswordField jPasswordFieldPASSWORD;
    private javax.swing.JRadioButton jRadioButtonCUSTOMERACCOUNT;
    private javax.swing.JRadioButton jRadioButtonSUPPLIERACCOUNT;
    private javax.swing.JTextField jTextFieldUSERNAME;
    // End of variables declaration//GEN-END:variables
}
